M48
; DRILL file {KiCad 9.0.1-9.0.1-0~ubuntu22.04.1} date 2025-06-25T02:24:25+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-25T02:24:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-9.0.1-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X120.775Y-109.625
X120.775Y-124.125
M30
